/**
 * Aioli Design System -- Landing Page
 *
 * The public-facing home page for the Aioli Design System. Replaces the
 * StudioWired IDE as the default entry point. Showcases the three-layer
 * architecture, token stats, built-in components, and quick-start guides.
 *
 * Follows the same dark-mode toggle pattern as Demo.jsx and Docs.jsx:
 *   document.documentElement.dataset.theme = 'dark' | delete
 *
 * Uses BEM naming throughout with the `.landing-` prefix.
 */

import React, { useState, useCallback, useEffect } from 'react';
import { COMPONENT_TEMPLATES } from '../../agents/component-generator-agent.js';
import CodeBlock from '../docs/components/CodeBlock';
import { useDarkMode } from '../hooks/useDarkMode';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Components to render in the live preview section. */
const PREVIEW_COMPONENTS = ['button', 'card', 'alert', 'badge', 'input', 'tabs'];

/** Feature cards for the features grid. */
const FEATURES = [
  {
    icon: '\uD83C\uDFA8',
    title: 'Design Tokens',
    desc: '1,543 tokens in W3C DTCG format across three tiers: primitives, semantic, and component-scoped. Build to CSS, JSON, or SCSS.',
  },
  {
    icon: '\uD83E\uDD16',
    title: 'AI Agents',
    desc: '6 specialized agents handle token management, accessibility validation, motion standards, component generation, code review, and orchestration.',
  },
  {
    icon: '\u267F',
    title: 'Accessibility First',
    desc: 'WCAG 2.1 AA enforced from the start. 120/120 contrast pairs pass across all 6 themes. Semantic HTML, ARIA, keyboard nav \u2014 not an afterthought.',
  },
  {
    icon: '\uD83E\uDDE9',
    title: '43 Components',
    desc: 'Atoms, molecules, organisms, templates, and full pages \u2014 all from natural language. 8 style modifiers and 4 page compositions built in.',
  },
  {
    icon: '\uD83D\uDD17',
    title: 'MCP Server',
    desc: '12 tools via Model Context Protocol. Plug Aioli into Claude, Cursor, Copilot, or any AI coding tool. No API keys required.',
  },
  {
    icon: '\uD83C\uDFAD',
    title: '6 Theme Presets',
    desc: 'Default, Glass, Neumorphic, Brutalist, Gradient, Dark Luxury \u2014 all WCAG AA verified. Derive a full palette from one brand color.',
  },
  {
    icon: '\uD83D\uDCE6',
    title: 'Community Registry',
    desc: 'Create, share, and install custom component packages. Scaffold with one command. Community components work with all entry points.',
  },
  {
    icon: '\uD83D\uDD04',
    title: 'Multi-Framework',
    desc: 'One prompt, any framework. Generate production code in HTML, React (JSX), Vue 3 (SFC), or Svelte from the same design tokens.',
  },
];

/** Stats shown in the hero ribbon. */
const HERO_STATS = [
  { value: '1,543', label: 'Design Tokens' },
  { value: '43', label: 'Components' },
  { value: '4', label: 'Frameworks' },
  { value: '6', label: 'AI Agents' },
  { value: '120/120', label: 'WCAG AA Pairs' },
];

/** Architecture layers for the diagram. */
const ARCHITECTURE_LAYERS = [
  {
    title: 'Tokens',
    desc: '1,543 W3C DTCG tokens: primitives \u2192 semantic \u2192 component',
  },
  {
    title: 'Agents',
    desc: '6 AI agents: token, a11y, motion, component, code review, orchestrator',
  },
  {
    title: 'Interfaces',
    desc: 'MCP Server (12 tools), REST API (13 endpoints), JS SDK (12 methods), CLI',
  },
  {
    title: 'Output',
    desc: 'HTML, React, Vue, Svelte, CSS custom properties, JSON',
  },
];

// ---------------------------------------------------------------------------
// Quick-start code snippets
// ---------------------------------------------------------------------------

const CLI_SNIPPET = `# Install
npm install aioli-design

# Generate a component in any framework
npx aioli-design generate "primary button" --format react

# Run accessibility audit
npx aioli-design audit`;

const SDK_SNIPPET = `import { createAioli } from 'aioli-design/sdk';

// No server needed -- direct mode
const aioli = await createAioli({
  mode: 'direct',
  tokensPath: './tokens'
});

// Natural language -> React component
const card = await aioli.generateComponent(
  'glassmorphic pricing card',
  { format: 'react' }
);
console.log(card.code); // Ready-to-use JSX`;

/** Framework showcase tabs and code snippets. */
const FRAMEWORK_TABS = ['HTML', 'React', 'Vue', 'Svelte'];

const FRAMEWORK_SNIPPETS = {
  HTML: `<!-- Generated by Aioli -->
<button class="btn btn--primary btn--lg"
        role="button" tabindex="0">
  <span class="btn__icon" aria-hidden="true">+</span>
  Get Started
</button>`,
  React: `// Generated by Aioli (format: 'react')
export default function AioliButton() {
  return (
    <button className="btn btn--primary btn--lg"
            role="button" tabIndex={0}>
      <span className="btn__icon" aria-hidden="true">+</span>
      Get Started
    </button>
  );
}`,
  Vue: `<!-- Generated by Aioli (format: 'vue') -->
<template>
  <button class="btn btn--primary btn--lg"
          role="button" tabindex="0">
    <span class="btn__icon" aria-hidden="true">+</span>
    Get Started
  </button>
</template>

<script setup>
// Aioli component -- no props needed
</script>`,
  Svelte: `<!-- Generated by Aioli (format: 'svelte') -->
<button class="btn btn--primary btn--lg"
        role="button" tabindex="0">
  <span class="btn__icon" aria-hidden="true">+</span>
  Get Started
</button>

<style>
  @import 'aioli-design/css/aioli.css';
</style>`,
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Default props so every template renders without "undefined" labels. */
const COMPONENT_DEFAULTS = {
  button:  { children: 'Button' },
  card:    { title: 'Card Title', content: 'Card body text goes here.' },
  alert:   {},
  badge:   { children: 'Badge', variant: 'primary' },
  input:   { label: 'Label', placeholder: 'Placeholder…' },
  tabs:    {},
};

/**
 * Safely render a component from COMPONENT_TEMPLATES.
 * The template is always a function that returns { html, tokens, a11y }.
 */
function renderComponent(name) {
  const tmpl = COMPONENT_TEMPLATES[name];
  if (!tmpl) return null;

  try {
    const defaults = COMPONENT_DEFAULTS[name] || {};
    const result = typeof tmpl.template === 'function'
      ? tmpl.template(defaults)
      : { html: tmpl.template || '' };
    const html = result.html || result;

    return (
      <div key={name} className="landing-preview__item">
        <div className="landing-preview__label">{name}</div>
        <div
          className="landing-preview__render"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      </div>
    );
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Main Landing component
// ---------------------------------------------------------------------------

export default function Landing() {
  // -- State ----------------------------------------------------------------

  const { darkMode, toggleDarkMode } = useDarkMode();
  const [installCopied, setInstallCopied] = useState(false);
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [activeFramework, setActiveFramework] = useState('HTML');

  // -- Mobile nav toggle ----------------------------------------------------

  const toggleMobileNav = useCallback(() => {
    setMobileNavOpen((prev) => !prev);
  }, []);

  const closeMobileNav = useCallback(() => {
    setMobileNavOpen(false);
  }, []);

  // Close mobile nav on resize to desktop
  useEffect(() => {
    const mq = window.matchMedia('(min-width: 769px)');
    const handler = () => { if (mq.matches) setMobileNavOpen(false); };
    mq.addEventListener('change', handler);
    return () => mq.removeEventListener('change', handler);
  }, []);

  // -- Copy install command to clipboard ------------------------------------

  const handleCopyInstall = useCallback(() => {
    navigator.clipboard.writeText('npm install aioli-design').then(() => {
      setInstallCopied(true);
      setTimeout(() => setInstallCopied(false), 2000);
    });
  }, []);

  // -- Render ---------------------------------------------------------------

  return (
    <div className="landing-page">

      {/* =================================================================== */}
      {/* HEADER (sticky)                                                     */}
      {/* =================================================================== */}
      <header className="landing-header">
        <div className="landing-header__left">
          <button
            type="button"
            className="landing-header__hamburger"
            onClick={toggleMobileNav}
            aria-label={mobileNavOpen ? 'Close navigation menu' : 'Open navigation menu'}
            aria-expanded={mobileNavOpen}
          >
            <span className="landing-header__hamburger-line" />
            <span className="landing-header__hamburger-line" />
            <span className="landing-header__hamburger-line" />
          </button>

          <a href="./" className="landing-header__logo">
            <svg className="landing-header__logo-mark" width="28" height="28" viewBox="0 0 120 120" fill="none" aria-hidden="true">
              <path d="M60 2 Q32 12, 20 38 Q12 60, 24 78 Q36 92, 50 82 Q58 76, 58 66 Q58 60, 60 58" stroke="currentColor" strokeWidth="4" fill="none" strokeLinecap="round" opacity="0.7"/>
              <path d="M60 2 Q88 12, 100 38 Q108 60, 96 78 Q84 92, 70 82 Q62 76, 62 66 Q62 60, 60 58" stroke="currentColor" strokeWidth="4" fill="none" strokeLinecap="round" opacity="0.7"/>
              <path d="M36 106 Q28 88, 32 70 Q36 54, 46 48 Q54 44, 58 52 Q60 56, 60 58" stroke="currentColor" strokeWidth="3" fill="none" strokeLinecap="round" opacity="0.45"/>
              <path d="M84 106 Q92 88, 88 70 Q84 54, 74 48 Q66 44, 62 52 Q60 56, 60 58" stroke="currentColor" strokeWidth="3" fill="none" strokeLinecap="round" opacity="0.45"/>
              <circle cx="60" cy="58" r="8" fill="currentColor"/>
            </svg>
            <span className="landing-header__wordmark"><span className="landing-header__wordmark-ai">Ai</span>oli</span>
          </a>
        </div>

        <nav className="landing-header__nav" aria-label="Main navigation">
          <a href="docs.html" className="landing-header__nav-link">
            Documentation
          </a>
          <a href="demo.html" className="landing-header__nav-link">
            Gallery
          </a>
          <a href="playground.html" className="landing-header__nav-link">
            Playground
          </a>
          <a href="theme.html" className="landing-header__nav-link">
            Themes
          </a>
          <a
            href="https://github.com/jaredhd/aioli"
            className="landing-header__nav-link"
            target="_blank"
            rel="noopener noreferrer"
          >
            GitHub
          </a>
        </nav>

        <button
          type="button"
          className="landing-header__toggle"
          onClick={toggleDarkMode}
          aria-label={darkMode ? 'Switch to light mode' : 'Switch to dark mode'}
        >
          {darkMode ? '\u2600\uFE0F' : '\uD83C\uDF19'}
        </button>
      </header>

      {/* Mobile nav overlay (visible only when hamburger is toggled) */}
      {mobileNavOpen && (
        <>
          <div
            className="landing-mobile-nav__backdrop"
            onClick={closeMobileNav}
            aria-hidden="true"
          />
          <nav
            className="landing-mobile-nav"
            aria-label="Mobile navigation"
          >
            <a href="docs.html" className="landing-mobile-nav__link" onClick={closeMobileNav}>
              Documentation
            </a>
            <a href="demo.html" className="landing-mobile-nav__link" onClick={closeMobileNav}>
              Component Gallery
            </a>
            <a href="playground.html" className="landing-mobile-nav__link" onClick={closeMobileNav}>
              Playground
            </a>
            <a href="theme.html" className="landing-mobile-nav__link" onClick={closeMobileNav}>
              Theme Builder
            </a>
            <a
              href="https://github.com/jaredhd/aioli"
              className="landing-mobile-nav__link"
              target="_blank"
              rel="noopener noreferrer"
              onClick={closeMobileNav}
            >
              GitHub
            </a>
          </nav>
        </>
      )}

      {/* =================================================================== */}
      {/* HERO                                                                */}
      {/* =================================================================== */}
      <section className="landing-hero">
        <p className="landing-hero__eyebrow">Free &amp; Open Source</p>
        <h1 className="landing-hero__title">
          AI-Powered Design for Everyone
        </h1>

        <p className="landing-hero__subtitle">
          The same design intelligence premium tools charge $20-50/month
          for &mdash; accessible, themed, production-quality UI from natural
          language &mdash; completely free. No API keys. No subscription. No
          vendor lock-in.
        </p>

        {/* -- Install command block ---------------------------------------- */}
        <div className="landing-hero__install">
          <code className="landing-hero__install-code">npm install aioli-design</code>
          <button
            type="button"
            className="landing-hero__install-copy"
            onClick={handleCopyInstall}
            aria-label="Copy install command"
          >
            {installCopied ? '\u2713 Copied' : 'Copy'}
          </button>
        </div>

        {/* -- CTA buttons ------------------------------------------------- */}
        <div className="landing-hero__actions">
          <a href="playground.html" className="landing-hero__cta landing-hero__cta--primary">
            Try the Playground &rarr;
          </a>
          <a href="docs.html" className="landing-hero__cta landing-hero__cta--outline">
            Read the Docs &rarr;
          </a>
        </div>

        {/* -- Stats ribbon ------------------------------------------------ */}
        <div className="landing-hero__stats">
          {HERO_STATS.map((stat) => (
            <div key={stat.label} className="landing-hero__stat">
              <span className="landing-hero__stat-value">{stat.value}</span>
              <span className="landing-hero__stat-label">{stat.label}</span>
            </div>
          ))}
        </div>
      </section>

      {/* =================================================================== */}
      {/* FEATURES GRID                                                       */}
      {/* =================================================================== */}
      <section className="landing-features">
        <h2 className="landing-features__heading">Everything Premium Tools Give You &mdash; For Free</h2>

        <div className="landing-features__grid">
          {FEATURES.map((feature) => (
            <div key={feature.title} className="landing-feature-card">
              <span className="landing-feature-card__icon" aria-hidden="true">
                {feature.icon}
              </span>
              <h3 className="landing-feature-card__title">{feature.title}</h3>
              <p className="landing-feature-card__desc">{feature.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* =================================================================== */}
      {/* FRAMEWORK SHOWCASE                                                  */}
      {/* =================================================================== */}
      <section className="landing-frameworks">
        <h2 className="landing-frameworks__heading">One Prompt, Any Framework</h2>
        <p className="landing-frameworks__subtitle">
          Generate production-ready components in your framework of choice.
          Same design tokens, same accessibility, same quality &mdash; different output.
        </p>

        <div className="landing-frameworks__tabs" role="tablist" aria-label="Framework output examples">
          {FRAMEWORK_TABS.map((tab) => (
            <button
              key={tab}
              type="button"
              role="tab"
              aria-selected={activeFramework === tab}
              className={`landing-frameworks__tab${activeFramework === tab ? ' landing-frameworks__tab--active' : ''}`}
              onClick={() => setActiveFramework(tab)}
            >
              {tab}
            </button>
          ))}
        </div>

        <div className="landing-frameworks__code" role="tabpanel" aria-label={`${activeFramework} output`}>
          <CodeBlock
            code={FRAMEWORK_SNIPPETS[activeFramework]}
            language={activeFramework === 'HTML' ? 'html' : activeFramework === 'React' ? 'jsx' : activeFramework === 'Vue' ? 'html' : 'html'}
            title={`${activeFramework} Output`}
          />
        </div>
      </section>

      {/* =================================================================== */}
      {/* LIVE COMPONENT PREVIEW                                              */}
      {/* =================================================================== */}
      <section className="landing-preview">
        <h2 className="landing-preview__heading">Built-In Components</h2>
        <p className="landing-preview__subtitle">
          Every component uses Aioli&apos;s own design tokens and passes WCAG AA
          accessibility standards.
        </p>

        <div className="landing-preview__grid">
          {PREVIEW_COMPONENTS.map((name) => renderComponent(name))}
        </div>
      </section>

      {/* =================================================================== */}
      {/* ARCHITECTURE DIAGRAM                                                */}
      {/* =================================================================== */}
      <section className="landing-architecture">
        <h2 className="landing-architecture__heading">Four-Layer Architecture</h2>

        <div className="landing-architecture__layers">
          {ARCHITECTURE_LAYERS.map((layer, i) => (
            <React.Fragment key={layer.title}>
              {i > 0 && (
                <div className="landing-architecture__arrow" aria-hidden="true">
                  &rarr;
                </div>
              )}
              <div className="landing-architecture__layer">
                <h3 className="landing-architecture__layer-title">{layer.title}</h3>
                <p className="landing-architecture__layer-desc">{layer.desc}</p>
              </div>
            </React.Fragment>
          ))}
        </div>
      </section>

      {/* =================================================================== */}
      {/* QUICK START                                                         */}
      {/* =================================================================== */}
      <section className="landing-quickstart">
        <h2 className="landing-quickstart__heading">Get Started in Seconds</h2>

        <div className="landing-quickstart__grid">
          <CodeBlock code={CLI_SNIPPET} language="bash" title="CLI" />
          <CodeBlock code={SDK_SNIPPET} language="js" title="JavaScript SDK" />
        </div>
      </section>

      {/* =================================================================== */}
      {/* FOOTER                                                              */}
      {/* =================================================================== */}
      <footer className="landing-footer">
        <div className="landing-footer__links">
          <a href="docs.html" className="landing-footer__link">Documentation</a>
          <a href="demo.html" className="landing-footer__link">Component Gallery</a>
          <a href="playground.html" className="landing-footer__link">Playground</a>
          <a href="theme.html" className="landing-footer__link">Theme Builder</a>
          <a
            href="https://github.com/jaredhd/aioli"
            className="landing-footer__link"
            target="_blank"
            rel="noopener noreferrer"
          >
            GitHub
          </a>
          <a
            href="https://www.npmjs.com/package/aioli-design"
            className="landing-footer__link"
            target="_blank"
            rel="noopener noreferrer"
          >
            npm
          </a>
        </div>

        <p className="landing-footer__copy">
          MIT License &mdash; Free forever. That&apos;s the point.
        </p>
      </footer>
    </div>
  );
}
