/**
 * Aioli Init Templates
 *
 * Defines what files each template includes and provides
 * scaffolding utilities for project initialization.
 */

import { existsSync, mkdirSync, copyFileSync, readdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = join(__dirname, '..', '..');
const PACKAGE_TOKENS_DIR = join(PACKAGE_ROOT, 'tokens');

// All component token files available
export const ALL_COMPONENTS = [
  'accordion.json',
  'alert.json',
  'avatar.json',
  'badge.json',
  'breadcrumb.json',
  'button.json',
  'card.json',
  'checkbox.json',
  'chip.json',
  'divider.json',
  'dropdown.json',
  'form-field.json',
  'input.json',
  'link.json',
  'modal.json',
  'navigation.json',
  'pagination.json',
  'popover.json',
  'progress.json',
  'radio.json',
  'rating.json',
  'select.json',
  'skeleton.json',
  'spinner.json',
  'stepper.json',
  'table.json',
  'tabs.json',
  'textarea.json',
  'toast.json',
  'toggle.json',
  'tooltip.json',
];

// Component display names for interactive prompts
export const COMPONENT_CHOICES = ALL_COMPONENTS.map(f => ({
  title: f.replace('.json', ''),
  value: f,
}));

// All primitive token files
const ALL_PRIMITIVES = ['colors.json', 'spacing.json', 'typography.json', 'radius.json', 'motion.json', 'borders.json'];

// All semantic token files
const ALL_SEMANTIC = ['colors.json', 'surfaces.json', 'dark.json', 'typography.json', 'elevation.json', 'z-index.json', 'focus.json', 'opacity.json'];

// Template definitions
export const TEMPLATES = {
  minimal: {
    name: 'Minimal',
    description: 'Primitive and semantic tokens only — lightweight starting point',
    primitives: ALL_PRIMITIVES,
    semantic: ['colors.json', 'surfaces.json'],
    components: [],
  },
  starter: {
    name: 'Starter',
    description: 'Primitives, semantic tokens, dark mode, and common component tokens',
    primitives: ALL_PRIMITIVES,
    semantic: ['colors.json', 'surfaces.json', 'dark.json', 'typography.json', 'elevation.json', 'focus.json'],
    components: ['button.json', 'input.json', 'card.json', 'form-field.json', 'badge.json', 'modal.json', 'link.json'],
  },
  full: {
    name: 'Full',
    description: 'Complete token set with all 31 component token files',
    primitives: ALL_PRIMITIVES,
    semantic: ALL_SEMANTIC,
    components: ALL_COMPONENTS,
  },
};

/**
 * Copy token files from the Aioli package into a target directory
 */
export function scaffoldTokens(targetDir, template) {
  const dirs = ['primitives', 'semantic', 'components'];

  for (const dir of dirs) {
    const targetSubDir = join(targetDir, 'tokens', dir);
    mkdirSync(targetSubDir, { recursive: true });

    const files = template[dir] || [];
    for (const file of files) {
      const src = join(PACKAGE_TOKENS_DIR, dir, file);
      const dest = join(targetSubDir, file);

      if (existsSync(src)) {
        copyFileSync(src, dest);
      }
    }
  }
}

/**
 * Generate Style Dictionary config for the target project
 */
export function generateConfig(targetDir) {
  const configContent = `/**
 * Style Dictionary Configuration
 * Generated by Aioli CLI
 */

export default {
  source: ['tokens/**/*.json'],

  // Enable DTCG format support ($value, $type, $description)
  usesDtcg: true,

  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/css/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            outputReferences: true
          }
        }
      ]
    },

    json: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.json',
          format: 'json/nested'
        }
      ]
    }
  }
};
`;

  writeFileSync(join(targetDir, 'config.js'), configContent, 'utf8');
}

/**
 * Generate .env.example with API key placeholder
 */
export function generateEnvExample(targetDir) {
  const content = `# Aioli Design System - Environment Variables
#
# Required for AI-powered component generation (aioli generate --ai)
# Get your key at: https://console.anthropic.com
ANTHROPIC_API_KEY=
`;

  writeFileSync(join(targetDir, '.env.example'), content, 'utf8');
}

/**
 * Generate a basic package.json for the new project
 */
export function generatePackageJson(targetDir, projectName) {
  const pkg = {
    name: projectName,
    version: '0.1.0',
    type: 'module',
    scripts: {
      build: 'aioli build',
      validate: 'aioli validate',
      audit: 'aioli audit',
    },
    dependencies: {
      aioli: '^0.1.0',
    },
  };

  writeFileSync(join(targetDir, 'package.json'), JSON.stringify(pkg, null, 2) + '\n', 'utf8');
}
